
---
- name: yum install packages for C++ development
  when: ansible_os_family == 'RedHat'
  yum: name={{item}} state=present
  with_items: "{{ cplusplusrpms }}"
  tags:
    - cplusplus

- include: tests.yml
  tags:
    - cplusplus
    - cplusplus_test
    - test
